#!/bin/sh

git clone https://github.com/turquoise-hexagon/cherry.git
git clone https://github.com/tryone144/compton.git
git clone https://github.com/adi1090x/rofi.git


mv rofi ~/.config/rofi/

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
